#  Workflow for building and uploading artifacts
name: Build/artifacts

on:
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      # Related https://github.com/electron-userland/electron-builder/issues/4181
      - name: Install libarchive-tools for pacman build
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install libarchive-tools
      # Checkout source & setup NodeJS
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }} 
      # Run the build
      - run: npm ci
      - run: npm run dist
      # Upload Mac
      - name: Archive Build Artifacts
        if: startsWith(matrix.os, 'macos')
        uses: actions/upload-artifact@v4
        with:
          name: artifact-mac
          overwrite: true
          if-no-files-found: error
          path: |
            release/*.*
      # Upload Linux
      - name: Archive Build Artifacts
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v4
        with:
          name: artifact-linux
          overwrite: true
          if-no-files-found: error
          path: |
            release/*.*
      # Upload Windows
      - name: Archive Build Artifacts
        if: startsWith(matrix.os, 'windows')
        uses: actions/upload-artifact@v4
        with:
          name: artifact-windows
          overwrite: true
          if-no-files-found: error
          path: |
            release/*.*